version: '2'
services:
  backend-application:
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    container_name: backend
    build:
      dockerfile: Dockerfile
    image: backend-budget-app:latest
    ports:
      - "8081:8080"
    networks:
      - budget-app-network
  db:
    container_name: pg_container
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - budget-app-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: finanse
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - budget-app-network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
networks:
  budget-app-network:
    driver: bridge
volumes:
  postgres-data: