spring:
  r2dbc:
    url: r2dbc:postgresql://pg_container/finanse?schema=public
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always